### ISSUE TITLE
Post-launch data sets

### ISSUE THREAD

**Issue by dweinberger** [Harvard-Open-Data-Project/harvard-open-data-project.github.io#10]
I would _love_ to see syllabi as a target data set. Because Harvard does not have an open syllabus project, these would have to be gathered via opt ins ... or possibly by downloading the syllabi the Open Syllabus Project at Columbia U has been gathering off the Web.  The OSP is also likely to be producing a useful schema; the people running it are pragmatic, not Schema Infinite Perfectionists. 

Why would I love this so much? 1. Syllabi are an insanely useful resource for faculty creating new courses. 2. Encouraging open syllabi would result in a cross-university dataset that would be a gold mine for researchers seeing to understand the patterns of ed in this country and beyond. 3. It seems to me to be totally in line with Harvard's commitment to openness. 4. Harvard syllabi could be imported into the H2O project that treats them like playlists to be learned from and mashed up.

**Comment by dweinberger** [comment]
We might want to partner early on with the Linked Data for Libraries (LD4L) project. It would show some of the power of DROID.

https://wiki.duraspace.org/pages/viewpage.action?pageId=41354028

LD4L is a Mellon-funded project from Cornell. The Harvard Library Innovation Lab and Stanford Library are the two invited partners. The aim is to created linked data stores of info useful to researchers, queryable across all three institutions. The data will be the three universities' library catalogs and other swaths of info, including (possibly) faculty info (pubs, topics, partners, etc.), images, archives, and some highly anonymized usage data. 

Linking to LD4L should be pretty straightforward since Harvard LibraryCloud's workflow engine will feed the Harvard LD ingestion engine, so if you can identify an object in LibraryCloud, you should be able to point to it in LD4L. At least I hope that's going to be the case, but I am no longer directly involved in the project. (I was the Harvard mgr of it until I left the Lab.) 

Paul Deschner has been the lead Harvard dev, with Jonathan Kennedy playing an increasingly important role. Randy Stern is the official manager, I believe. deschner@law.harvard.edu.   Jonathan_Kennedy@hms.harvard.edu   randy_stern@harvard.edu

The project is 1.4 years into a 2 yr project. Launch is in Dec. 2015.

**Comment by drewrwilson** [comment]
I'd like to see data about Harvard's investments in fossil fuels

...then I'd like [Harvard to drop all those investments](http://harvardheatweek.org/).

Please & thank you :)

**Comment by nsinai** [comment]
Thanks @drewrwilson!  Do you know what data is publicly available about this topic today?

**Comment by drewrwilson** [comment]
@nsinai I am not aware of a place to start with this data although I would be interested in the info. Similar to open gov data, starting with the budget is a great idea. eg: What money comes in and from where? What investments exist and what are the details about them? Where is money spent? etc etc

**Comment by perryhewitt** [comment]
International stats might be worth considering: http://www.hio.harvard.edu/statistics
