### ISSUE TITLE
Public Feedback and Engagement Mechanisms

### ISSUE THREAD

**Issue by rebeccawilliams** [Harvard-Open-Data-Project/harvard-open-data-project.github.io#14]
To solicit general Ux feedback or feedback on what datasets should be included in Droid at launch or after (#8, #10), it'd be great to partner with Boston's new library project on open data: http://www.cityofboston.gov/doit/knight.asp

For reference: Pittsburgh has similarly partnered with the University of Pittsburgh on a regional open data catalog: http://ucsur.pitt.edu/programs/urban-regional-analysis/regional-data-center/

See also these engagement strategies: 
- [Montgomery County: Open Data Town Hall](http://www6.montgomerycountymd.gov/apps/News/press/PR_details.asp?PrID=13107)
- [New York City: Transparency Working Group](http://nyctwg.org/)
- [Philadelphia: Open Data Race](https://www.opendataphilly.org/contest)
- _[and these resources](https://github.com/project-open-data/project-open-data.github.io/issues/439)_

**Comment by nsinai** [comment]
Thanks @rebeccawilliams -- great suggestions!  cc @perryhewitt

**Comment by perryhewitt** [comment]
I know the person at BPL who led this (I recruited her to Harvard!) -- can get an intro. 

People might also be interested in this Pew report on Americans' views of open government data:  http://www.pewinternet.org/2015/04/21/open-government-data/

**Comment by nsinai** [comment]
That is a fascinating report!  Interesting to see how people's view of open data is consistent with their feelings on government generally.
