### ISSUE TITLE
License for Harvard's Open Data website

### ISSUE THREAD

**Issue by nsinai** [Harvard-Open-Data-Project/harvard-open-data-project.github.io#3]
This thread is to discuss license options for Harvard's Open Data website (not the underlying datasets).

For comparison, here is Data.gov's license: https://github.com/GSA/data.gov/blob/master/LICENSE.md

Here is a straw man for discussion:

_Public Domain_

We waive copyright and related rights in the work worldwide through the CC0 1.0 Universal public domain dedication.

All contributions to this project will be released under the CC0 dedication. By submitting a pull request, you are agreeing to comply with this waiver of copyright interest. See CONTRIBUTING for more information.

_GNU General Public License_

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

Visit http://www.gnu.org/licenses/ to learn more about the GNU General Public License.

_Other Information_

In no way are the patent or trademark rights of any person affected by CC0, nor are the rights that other persons may have in the work or in how the work is used, such as publicity or privacy rights.

Unless expressly stated otherwise, the person who associated a work with this deed makes no warranties about the work, and disclaims liability for all uses of the work, to the fullest extent permitted by applicable law. When using or citing the work, you should not imply endorsement by the author or the affirmer.

**Comment by nsinai** [comment]
@jimwaldo -- do you think University attorneys might respond in this thread?

**Comment by jimwaldo** [comment]
So, I've talked with folks from the OGC (Office of General Counsel-- I've been spending too much time in the Smith Center building). They are of the opinion that we don't need a license on the data-- that copyright is the correct way to protect Harvard's interests in this. Since this is simple and requires no additional work, I'm willing to believe them. Let's just go with that and leave it with no license.
