### ISSUE TITLE
License for datasets

### ISSUE THREAD

**Issue by nsinai** [Harvard-Open-Data-Project/harvard-open-data-project.github.io#5]
This thread can be for a discussion of the license options for the underlying datasets listed on Harvard's Open Data website.

Would suggest 3 popular options, with the default and recommended choice being CC0.

**Comment by rebeccawilliams** [comment]
+1 to CC0. It'd be great to have dataset licenses listed as a URL for consistent structured analysis. Below are some *open* options: 

Worldwide Public Domain Dedications

* Creative Commons Zero Public Domain Dedication (CC0), e.g. "license":"https://creativecommons.org/publicdomain/zero/1.0/"
* Open Data Commons Public Domain Dedication and Licence (PDDL), e.g. "license":"http://opendatacommons.org/licenses/pddl/1.0/"

Open Licenses  
* Open Data Commons Attribution License (ODC-By), e.g. "license":"http://opendatacommons.org/licenses/by/1.0/"
* Open Data Commons Open Database License (ODbL), e.g. "license":"http://opendatacommons.org/licenses/odbl/1.0/"
* Creative Commons Attribution (CC BY), e.g. "license":"https://creativecommons.org/licenses/by/4.0/"
* Creative Commons Attribution-ShareAlike (CC BY-SA), e.g. "license":"https://creativecommons.org/licenses/by-sa/4.0/"
* GNU Free Documentation License, e.g. "license":"http://www.gnu.org/licenses/fdl-1.3.en.html"

**Comment by nsinai** [comment]
Thanks @rebeccawilliams !
