### ISSUE TITLE
Data sets for launch

### ISSUE THREAD

**Issue by nsinai** [Harvard-Open-Data-Project/harvard-open-data-project.github.io#8]
This thread is for discussion of which data sets should be included in launch

**Comment by dweinberger** [comment]
LibraryCloud provides API access to about 17M items: The 13M items (books, etc.) in the Harvard Library collections, images in VIA, and archival records at an unusual level of granularity. It's been up and in service since Dec. 2014. There are probably some cool demos that could be done integrating other data sets with Library content.

**Comment by nsinai** [comment]
Thanks David!  Can you provide the URL and a contact person?

**Comment by dweinberger** [comment]
D'oh.

http://library.harvard.edu/librarycloud/ is the overview.

Randy Stern at Library Technology Services is the manager of the project: randy_stern@harvard.edu

Paul Deschner of the Library innovation Lab has been deeply involved in LibraryCloud and developed the first version of it (now called "lilCloud" -- more experimental, more weird types of data in it). deschner@law.harvard.edu

**Comment by dweinberger** [comment]
Harvard Faculty Finder? https://www.faculty.harvard.edu/Scholarship_and_Research/Faculty_Scholarship/Harvard_Faculty_Finder

**Comment by perryhewitt** [comment]
DINING & NUTRITION MODULE

Group:            Dining Services

Contact 1:    Crista Martin, Director for Marketing and Communications, crista_martin@harvard.edu, (617) 496-6705

Contact 1 (for feed    Kim Ho, Associate Director, CSOL Applied Technologies,
Related issues):    kim_ho@harvard.edu, (617) 496-6717   

Data source/Feed:    CSV from dining (Menu.csv and Menu2.csv)
Uploaded to a Dropbox account (per Kim via email on 11/25/14)
IP addresses from dining: 128.103.161 128.103.95.54

Website:        http://www.dining.harvard.edu/residential_dining/menus.html

**Comment by rebeccawilliams** [comment]
+ Expenditures; all of this line item data behind: http://finance.harvard.edu/annual-report in CSV format (is that available elsewhere?)
+ Procurement Data (in accordance with these guidelines: http://sunlightfoundation.com/procurement/opendataguidelines) 
+ Reported Sexual Assaults & post it here: https://www.notalone.gov/data/
+ Campus Police Log in a structured format (eg CSV): http://www.hupd.harvard.edu/public-police-log
+ Web Analytics

**Comment by dweinberger** [comment]
The Faculty Finder -- a faculty registsry -- has an API: http://api.facultyfinder.harvard.edu/
It's a linked data repository, but there's a [SPARQL endpoint](http://api.facultyfinder.harvard.edu/public/SPARQL/ProfilesSPARQLAPI.svc/search) and an [XML search API](http://api.facultyfinder.harvard.edu/public/Search/ProfilesSearchAPI.svc/search)

**Comment by nsinai** [comment]
Possible Data Sets (from the Read Me of this project): 

Q scores
Course catalog
Shuttle tracker
Dining hall menus
Demographics from the FAS Registrar
Endowment
Library search
Harvard art museum collections
Building plans for Allston
Authentication
DASH research repository

**Comment by dweinberger** [comment]
A nit: I'd suggest changing "Library Search" to "LibraryCloud." Search is obviously not a data source. LibraryCloud is the best and fully open way of searching the Library's metadata.

**Comment by hathix** [comment]
Good call. Also, I'll add the other data sets referenced here to the list.

**Comment by hathix** [comment]
A few more links we should look into:

- http://oir.harvard.edu/fact-book
- http://home.hppm.harvard.edu/hppm-unit/information-resources
- http://map.harvard.edu/
- http://www.harvard.edu/on-campus/research
- https://www.campusservices.harvard.edu/energy-facilities

**Comment by hathix** [comment]
Some more potentially interesting datasets we should look into:

- More shuttle tracker info
- Energy usage by building
- List of faculty
- Financial data for all schools
- List of all scholarships and funding available across university
- Coop book catalog

**Comment by hathix** [comment]
If you find metadata on some good datasets, please fill out this form!
https://docs.google.com/forms/d/1KpVH2juCOnFI3bcKy5sEOI_uedyGDnwXfueNV3aYmzs/viewform

**Comment by nsinai** [comment]
@hathix -- where is the link to the metadata collected from your above link?  Thanks!
